Model, Fixed fineOne incorrect initial order
ice/framework pull request #175
Opened 2018-09-12 05:58 UTC by Yahasana

initial model data should go ahead `initialize`

2018-09-12 06:53 UTC, mruz commented
But then we will get the `Not found` exception if no result, previously it was `false`.
```php
$u = Users::findOne(['username' => 'abcd']);
```

2018-09-12 11:14 UTC, Yahasana commented
Model should be fine now. it's there exact release date for v1.4.0 ? @mruz

2018-09-12 11:23 UTC, mruz commented
I'll add some tests for the model and merge after. Just to be sure it's working fine. 
There is no strict release date atm.

2018-09-12 14:51 UTC, Yahasana commented
Initial flow test case
```php
class TestModel extends Model
{
    public function __construct($filters = null, array $data = [])
    {
        echo 'model contruct begin';
        parent::__construct($filters, $data);
        echo 'model contruct done';
        print_r($this->all());
    }
    public function onContruct()
    {
        echo 'model contructing...';
        print_r($this->all());
        echo 'model set columnName=onContruct';
        $this->set('columnName', 'onContruct'); // real columnName
    }
    public function initialize()
    {
        echo 'model initialize...';
        print_r($this->all());
        echo 'model set columnName=initialize';
        $this->set('columnName', 'initialize'); // real columnName
    }
}
```

2018-09-14 08:05 UTC, mruz commented
I pushed few db/model tests. Could you please rebase your branch?
```
git remote add upstream https://github.com/ice/framework.git
git fetch upstream
git rebase upstream/dev
git push origin patch-10
```

2018-09-14 11:02 UTC, Yahasana commented
it'd be bug of unitest. after some investigations, you can't write unitest case for `static` things like as `non-static` one

2018-09-14 11:57 UTC, mruz requested changes
It would be good to continue in #183

2018-09-14 11:57 UTC, mruz commented on ice/mvc/model.zep
> -                let instances[] = create_instance_params(get_called_class(), [null, data]);
As I remember I had some issues with static implementation on zephir and that's why I used
```zep
create_instance_params(get_called_class(), [null, data]);
```

2018-09-14 11:57 UTC, mruz commented on ice/mvc/model.zep
> +        let model = new static(filters, options);
Options are not the same as data in construct.

Options are passed to the db::find query
```
// eg. find the latest active user
$user = User::findOne(['status' => 1], ['order' => 'id DESC']);
```

Data is used to populate the fields
```
// fills the $user->data attribute
$user = new User(null, ['username' => 'ice', 'status' => 1]);
```

2018-09-14 14:45 UTC, Yahasana commented
new [pr](https://github.com/ice/framework/pull/185)

2018-09-14 14:45 UTC, closed without merging